[project]
name = "de-rerum-computabilium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.5.0",
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "scipy>=1.18.1",
]

[project.scripts]
drc = "de_rerum_computabilium.cli:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mkdocs-material>=9.7.7",
    "mypy>=2.3.1",
    "ruff>=0.16.6",
]
